---
# This file contains example of several GemInstaller features.  Your file can be simpler
defaults: # defaults apply to all gems in the 'gems:' section, but can be overridden
  # '--include-dependencies' is only needed for RubyGems < 1.0
  # install_options: --include-dependencies
gems:
- name: capistrano
  version: >= 2.5.4
- name: geminstaller
  version: >= 0.5.0
- name: gnuplot
  version: >= 2.2
- name: mocha
  version: 0.9.5
- name: mongrel
  version: 1.1.5
- name: mongrel_cluster
  version: 1.0.5
- name: RedCloth
  version: >= 4.1.1
- name: rubyforge
  version: 1.0.2
- name: spicycode-rcov
  version: 0.8.1.5.0
- name: twitter4r
  version: >= 0.3.0
- name: xml-simple
  version: 1.0.11
<%= include_config("#{File.expand_path(File.dirname(__FILE__))}/geminstaller_rails.yml") %>